export const GET_ERRORS = 'GET_ERRORS'
export const CLEAN_REGISTER_ERRORS = 'CLEAN_REGISTER_ERRORS'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILES = 'GET_PROFILES'
export const PROFILE_LOADING = 'GET_PROFILE_LOADING'
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND'
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE'

